export class Personal {
    public PP1: any;
    public PP2: any;
    public PP3: any;
    public PP4: any;
    public PP5: any;
    public PP6: any;
    public PP7: any;
    public PP8: any;
    public PP9: any;
    public PP10: any;
    public PP11: any;
    public PP12: any;
    public PP13: any;
    public PP14: any;
    public PP15: any;
    public PP16: any;
    public PP17: any;
    public PP18: any;
    public PP19: any;
    public PP20: any;

    public RP1: any;
    public RP2: any;
    public RP3: any;
    public RP4: any;
    public RP5: any;
    public RP6: any = { Palpitaciones: '', Taquicardias: '', Nauseas: '', Desmayos: '' };
    public RP7: any = { Obesidad: '', Estres: '', Tabaquismo: '', Sedentarismo: '' };
    public RP8: any;
    public RP9: any;
    public RP10: any;
    public RP11: any;
    public RP12: any;
    public RP13: any;
    public RP14: any;
    public RP15: any;
    public RP16: any;
    public RP17: any;
    public RP18: any;
    public RP19: any;
    public RP20: any;

    public Cuales1: any;
    public Cuales9: any;
    public Cuales10: any;
    public Cuales11: any;
    public Cuales17: any;
    public Cuales19: any;
    public Cuales20: any;
    public Anno1: any;
    public Anno2: any;
    public Anno3: any;
    public Anno4: any;
    public Anno5: any;
    public Anno8: any;
    public Anno9: any;
    public Anno10: any;
    public Anno11: any;
    public Anno12: any;
    public Anno13: any;
    public Anno14: any;
    public Anno15: any;
    public Anno16: any;
    public Anno17: any;
    public Anno19: any;
    public Anno20: any;

    constructor() {
        this.PP1 = '';
        this.PP2 = '';
        this.PP3 = '';
        this.PP4 = '';
        this.PP5 = '';
        this.PP6 = '';
        this.PP7 = '';
        this.PP8 = '';
        this.PP9 = '';
        this.PP10 = '';
        this.PP11 = '';
        this.PP12 = '';
        this.PP13 = '';
        this.PP14 = '';
        this.PP15 = '';
        this.PP16 = '';
        this.PP17 = '';
        this.PP18 = '';
        this.PP19 = '';
        this.PP20 = '';
        this.RP1 = '';
        this.RP2 = '';
        this.RP3 = '';
        this.RP4 = '';
        this.RP5 = '';
        this.RP8 = '';
        this.RP9 = '';
        this.RP10 = '';
        this.RP11 = '';
        this.RP12 = '';
        this.RP13 = '';
        this.RP14 = '';
        this.RP15 = '';
        this.RP16 = '';
        this.RP17 = '';
        this.RP18 = '';
        this.RP19 = '';
        this.RP20 = '';
        this.RP6 = { Palpitaciones: '', Taquicardias: '', Nauseas: '', Desmayos: '' };
        this.RP7 = { Obesidad: '', Estres: '', Tabaquismo: '', Sedentarismo: '' };
        this.Cuales1 = '';
        this.Cuales9 = '';
        this.Cuales10 = '';
        this.Cuales11 = '';
        this.Cuales17 = '';
        this.Cuales19 = '';
        this.Cuales20 = '';
        this.Anno1 = '';
        this.Anno2 = '';
        this.Anno3 = '';
        this.Anno4 = '';
        this.Anno5 = '';
        this.Anno8 = '';
        this.Anno9 = '';
        this.Anno10 = '';
        this.Anno11 = '';
        this.Anno12 = '';
        this.Anno13 = '';
        this.Anno14 = '';
        this.Anno15 = '';
        this.Anno16 = '';
        this.Anno17 = '';
        this.Anno19 = '';
        this.Anno20 = '';
    }

}

